# AUTOGENERATED! DO NOT EDIT! File to edit: BERT.ipynb (unless otherwise specified).

__all__ = []

# Cell
from ModernArchitecturesFromPyTorch.nb_ScratchToPytorch import *
import math
from nbdev.showdoc import show_doc