
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/BERT.ipynb
from ModernArchitecturesFromPyTorch.nb_ScratchToPytorch import *
import math