
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/GRU.ipynb
from ModernArchitecturesFromPyTorch.nb_ScratchToPytorch import *
from ModernArchitecturesFromScratch.convolutions_pooling_04 import *